# Generated by Django 5.1 on 2024-08-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAcervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/galleries/acervo')),
                ('title', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryAguasMarginais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/galleries/aguasmarginais')),
                ('title', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPantanalBrasileiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/galleries/pantanal')),
                ('title', models.CharField(max_length=600)),
            ],
        ),
    ]
